CREATE TABLE IF NOT EXISTS habits(
    habit_id INTEGER PRIMARY KEY AUTOINCREMENT,
    habit_name TEXT NOT NULL UNIQUE,
    created_at DATE NOT NULL DEFAULT(DATE('now'))
);

CREATE TABLE IF NOT EXISTS notes(
    note_id INTEGER PRIMARY KEY AUTOINCREMENT,
    date DATE NOT NULL DEFAULT(DATE('now')),
    note TEXT NOT NULL
    UNIQUE(date)
);

CREATE TABLE IF NOT EXISTS daily_log(
    log_id INTEGER PRIMARY KEY AUTOINCREMENT,
    date DATE NOT NULL DEFAULT(DATE('now')),
    habit_id INTEGER NOT NULL,
    completed INTEGER NOT NULL,

    UNIQUE (habit_id,date),
    FOREIGN KEY (habit_id) REFERENCES habits(habit_id) ON DELETE CASCADE
);