def get_dark_stylesheet():
    return"""                  QWidget{
                               background-color:#121212;
                               font-family:Segoe UI;
                               }
                               QFrame{
                               background-color:#1E1E1E;
                               border-radius:15px;
                               }
                               QFrame#inner_frames{
                               background-color:#252525;
                               border-radius:10px;
                               padding-top:15px;
                               padding-bottom:15px;
                               }
                               QFrame#centerFrame{
                               border:2px solid #3B82F6;
                               }
                               QLabel{
                               background:transparent;
                               color:#FBB03B;
                               font-size:24px;
                               }
                               QLabel#sideHeaders{
                               min-height:50px;
                               }
                               QLabel#statName{
                               color:#C5C5C5;
                               font-size:18px;
                               font-weight:500;
                               }
                               QLabel#statValue{
                               color:#B8B8B8;
                               font-size:20px;
                               font-weight:500;
                               }
                               QLabel#progress{
                               color:#3B82F6;
                               font-weight:500;
                               font-size:20px;
                               }
                               QLabel#streak{
                               color:#FBB03B;
                               font-weight:500;
                               font-size:20px;
                               }
                               QLabel#streakDays{
                               color:#FBB03B;
                               font-size:50px;
                               font-weight:400;
                               font-style:italic;
                               }
                               QLabel#daysLabel{
                               color:#E5E5E5;
                               font-size:22px;
                               padding-top:18px;
                               }
                               QLabel#keepLabel{
                               color:#C5C5C5;
                               font-size:18px;
                               padding-left:30px;
                               }
                               QLabel#percentLabel{
                               color:#3B82F6;
                               font-size:24px;
                               font-weight:450;
                               }
                               QLabel#finishedLabel{
                               color:#3B82F6;
                               font-size:24px;
                               font-weight:450;
                               }
                               QLabel#dateLabel{
                               color:#C5C5C5;
                               font-size:20px;
                               }
                               QLabel#todayLabel{
                               color:#FBB03B;
                               font-size:34px;
                               font-weight:460;
                               }
                               QLabel#notesHeader{
                               color:#FBB03B;
                               font-size:24px;
                               font-weight:500;
                               }
                               QLabel#errorLabel{
                               color:#EF4444;
                               font-size:14px;
                               }
                               QTextEdit{
                               background-color:#1E1E1E;
                               color:#E5E5E5;
                               border:none;
                               border-radius:10px;
                               padding:10px;
                               selection-background-color:#3B82F6;
                               font-size:18px;
                               }
                               QTextEdit::focus{
                               border:2px solid #3B82F6;
                               }
                               QListWidget{
                               background-color:#252525;
                               color:#FBB03B;
                               border:none;
                               border-radius:10px;
                               font-size:18px;
                               padding:10px;
                               }
                               QListWidget::item{
                               padding:10px;
                               min-height:25px;
                               }
                               QListWidget::item:selected{
                               background-color:#3B82F6;
                               color:white;
                               border-radius:6px;
                               }
                               QProgressBar{
                               border:none;
                               border-radius:6px;
                               background:#363636;
                               height:12px;
                               }
                               QProgressBar::chunk{
                               background:#3B82F6;
                               border-radius:6px;
                               }
                               QLineEdit{
                               background-color:#252525;
                               color:#FBB03B;
                               font-size:18px;
                               min-height:25px;
                               border:none;
                               border-radius:10px;
                               padding:8px;
                               }
                               QLineEdit:focus{
                               border:2px solid #3B82F6;
                               }
                               QCalendarWidget QWidget{
                               background-color:#252525;
                               }
                               QCalendarWidget QToolButton{
                               background-color:#252525;
                               color:#FBB03B;
                               border-radius:6px;
                               border:none;
                               padding:4px;
                               font-size:20px;
                               font-weight:600;
                               }
                               QCalendarWidget QToolButton:hover{
                               background-color:#333333;
                               }
                               QCalendarWidget QToolButton:pressed{
                               background-color:#404040;
                               }
                               QCalendarWidget QMenu{
                               background-color:#252525;
                               color:#FBB03B;
                               }
                               QCalendarWidget QAbstractItemView{
                               selection-background-color:#3B82F6;
                               selection-color:white;
                               }
                               QCalendarWidget QTableView{
                               background-color:#252525;
                               alternate-background-color:#252525;
                               }
                               QCalendarWidget QHeaderView{
                               background-color:#252525;
                               }
                               QCalendarWidget QTableView QHeaderView::section{
                               background-color:#252525;
                               color:#FBB03B;
                               padding:6px;
                               border:none;
                               }
                               QPushButton{
                               border:none;
                               border-radius:10px;
                               padding:8px;
                               font-size:15px;
                               min-height:40px;
                               }
                               QPushButton#saveBtn{
                               background-color:#16A34A;
                               color:white;
                               font-size:18px;
                               font-weight:450;
                               }
                               QPushButton#saveBtn:hover{
                               background-color:#22C55E;
                               }
                               QPushButton#saveBtn:pressed{
                               background-color:#15803D;
                               }
                               QPushButton#add_habit{
                               background-color:#3B82F6;
                               color:white;
                               }
                               QPushButton#delete_habit{
                               background-color:#B91C1C;
                               color:white;
                               }
                               QPushButton#add_habit:hover{
                               background-color:#60A5FA;
                               }
                               QPushButton#add_habit:pressed{
                               background-color:#2563EB;
                               }
                               QPushButton#delete_habit:hover{
                               background-color:#DC2626;
                               }
                               QPushButton#delete_habit:pressed{
                               background-color:#991B1B;
                               }
                               QTableWidget{
                               background-color:#1E1E1E;
                               color:#E5E5E5;
                               border:none;
                               border-radius:10px;
                               gridline-color:#2F2F2F;
                               font-size:16px;
                               selection-background-color:transparent;
                               outline:none;
                               }
                               QHeaderView::section{
                               background-color:#252525;
                               color:#FBB03B;
                               border:1px solid #1E1E1E;
                               padding:8px;
                               font-size:16px;
                               font-weight:450;
                               }
                               QTableWidget::item:selected{
                               background-color:#3B82F6;
                               }
                               QScrollBar:horizontal{
                               background:rgb(0,0,0);
                               height:12px;
                               border:none;
                               border-radius:6px;
                               }
                               QScrollBar::handle:horizontal{
                               background:#3B82F6;
                               border-radius:6px;
                               min-width:12px;
                               }
                               QScrollBar::handle:horizontal:hover{
                               background:#60A5FA;
                               }
                               QScrollBar::add-line:horizontal,
                               QScrollBar::sub-line:horizontal{
                               width:0px;
                               }
                               QScrollBar::add-page:horizontal,
                               QScrollBar::sub-page:horizontal{
                               background:none;
                               }
                               QScrollBar:vertical{
                               background:rgb(0,0,0);
                               width:12px;
                               border:none;
                               border-radius:6px;
                               }
                               QScrollBar::handle:vertical{
                               background:#3B82F6;
                               border-radius:6px;
                               min-height:12px;
                               }
                               QScrollBar::handle:vertical:hover{
                               background:#60A5FA;
                               }
                               QScrollBar::add-line:vertical,
                               QScrollBar::sub-line:vertical{
                               height:0px;
                               }
                               QScrollBar::add-page:vertical,
                               QScrollBar::sub-page:vertical{
                               background:transparent;
                               }
                               QCheckBox{
                               background:transparent;
                               }
                               QCheckBox::indicator{
                               width:18px;
                               height:18px;
                               border:2px solid rgba(220,38,38,150);
                               border-radius:4px;
                               background-color:rgba(220,38,38,55);
                               image:url("./python/dailytracker/cross.svg");
                               }
                               QCheckBox::indicator:hover{
                               border:2px solid rgba(239,68,68,200);
                               background-color:rgba(239,68,68,80);
                               }
                               QCheckBox::indicator:pressed{
                               background-color:rgba(230,68,68,90);
                               }
                               QCheckBox::indicator:checked{
                               background-color:rgba(22,163,74,90);
                               border:2px solid rgba(22,163,74,220);
                               image:url("./python/dailytracker/check.svg");
                               }
                               QCheckBox::indicator:checked:hover{
                               background-color:rgba(34,197,94,110);
                               border:2px solid rgba(34,197,94,225);
                               }
                               QCheckBox::indicator[future ="true"]{
                               background-color:#252525;
                               border:2px solid #3A3A3A;
                               image:none;
                               }
                               QCheckBox::indicator[before_creation ="true"]{
                               background-color:#252525;
                               border:2px solid #3A3A3A;
                               image:none;
                               }
                               QPushButton#themeToggleBtn{
                               background:transparent;
                               border:none;
                               border-radius:14px;
                               padding:0px;
                               /*min-height:0px;
                               max-height:0px;*/
                               }
                               QPushButton#themeToggleBtn:hover{
                               background-color:rgba(251,176,59,30);
                               }
                               QPushButton#themeToggleBtn:pressed{
                               background-color:rgba(251,176,59,50)
                               }
                               QFrame#bottomBar{
                               background-color:#0D0D0D;
                               border-radius:0px;
                               border-top:1px solid #2A2A2A;
                               }
                               QLabel#bottomBarText{
                               color:#C5C5C5;
                               font-size:18px;
                               font-weight:400px;
                               }
                               """
def get_light_stylesheet():
    return """
                    QWidget{
                        background-color:#F8FAFC;
                        font-family:"Segoe UI";
                    }
                    QFrame{
                        background-color:#FFFFFF;
                        border-radius:15px;
                    }
                    QFrame#inner_frames{
                        background-color:#F9FAFB;
                        border:1px solid #ECEFF3;
                        border-radius:10px;
                        padding-top:15px;
                        padding-bottom:15px;
                    }
                    QFrame#centerFrame{
                        border:2px solid #3B82F6;
                    }
                    QLabel{
                        background:transparent;
                        color:#A66A00;
                        font-size:24px;
                    }
                    QLabel#sideHeaders{
                        min-height:50px;
                    }
                    QLabel#statName{
                        color:#64748B;
                        font-size:18px;
                        font-weight:500;
                    }
                    QLabel#statValue{
                        color:#1F2937;
                        font-size:20px;
                        font-weight:500;
                    }
                    QLabel#progress{
                        color:#3B82F6;
                        font-weight:500;
                        font-size:20px;
                    }
                    QLabel#streak{
                        color:#A66A00;
                        font-weight:500;
                        font-size:20px;
                    }
                    QLabel#streakDays{
                        color:#A66A00;
                        font-size:50px;
                        font-weight:400;
                        font-style:italic;
                    }
                    QLabel#daysLabel{
                        color:#334155;
                        font-size:22px;
                        padding-top:18px;
                    }
                    QLabel#keepLabel{
                        color:#64748B;
                        font-size:18px;
                        padding-left:30px;
                    }
                    QLabel#percentLabel{
                        color:#3B82F6;
                        font-size:24px;
                        font-weight:450;
                    }
                    QLabel#finishedLabel{
                        color:#3B82F6;
                        font-size:24px;
                        font-weight:450;
                    }
                    QLabel#dateLabel{
                        color:#64748B;
                        font-size:20px;
                    }
                    QLabel#todayLabel{
                        color:#A66A00;
                        font-size:34px;
                        font-weight:460;
                    }
                    QLabel#notesHeader{
                        color:#A66A00;
                        font-size:24px;
                        font-weight:500;
                    }
                    QLabel#errorLabel{
                        color:#DC2626;
                        font-size:14px;
                    }
                    QTextEdit{
                        background-color:#FFFFFF;
                        color:#1F2937;
                        border:1px solid #CBD5E1;
                        border-radius:10px;
                        padding:10px;
                        selection-background-color:#3B82F6;
                        font-size:18px;
                    }
                    QTextEdit:focus{
                        border:2px solid #3B82F6;
                    }
                    QListWidget{
                        background-color:#F9FAFB;
                        color:#A66A00;
                        border:1px solid #E5E7EB;
                        border-radius:10px;
                        font-size:18px;
                        padding:10px;
                    }
                    QListWidget::item{
                        padding:10px;
                        min-height:25px;
                        border-radius:8px;
                    }
                    QListWidget::item:hover{
                        background-color:#EFF6FF;
                    }
                    QListWidget::item:selected{
                        background-color:#3B82F6;
                        color:white;
                        border-radius:8px;
                    }
                    QProgressBar{
                        border:none;
                        border-radius:6px;
                        background:#E2E8F0;
                        height:12px;
                    }
                    QProgressBar::chunk{
                        background:#3B82F6;
                        border-radius:6px;
                    }
                    QLineEdit{
                        background-color:#FFFFFF;
                        color:#1F2937;
                        font-size:18px;
                        min-height:25px;
                        border:1px solid #CBD5E1;
                        border-radius:10px;
                        padding:8px;
                    }
                    QLineEdit:focus{
                        border:2px solid #3B82F6;
                    }
                    QCalendarWidget QWidget{
                        background-color:#F9FAFB;
                        color:#1F2937;
                    }
                    QCalendarWidget QToolButton{
                        background-color:#F9FAFB;
                        color:#A66A00;
                        border-radius:8px;
                        border:none;
                        padding:5px;
                        font-size:20px;
                        font-weight:600;
                    }
                    QCalendarWidget QToolButton:hover{
                        background-color:#EDF4FF;
                        color:#3B82F6;
                    }
                    QCalendarWidget QToolButton:pressed{
                        background-color:#DCEBFF;
                    }
                    QCalendarWidget QMenu{
                        background-color:#FFFFFF;
                        color:#1F2937;
                        border:1px solid #E5E7EB;
                    }
                    QCalendarWidget QAbstractItemView{
                        selection-background-color:#3B82F6;
                        selection-color:white;
                        outline:none;
                    }
                    QCalendarWidget QTableView{
                        background-color:#F9FAFB;
                        alternate-background-color:#F9FAFB;
                        color:#1F2937;
                        gridline-color:#ECECEC;
                    }
                    QCalendarWidget QHeaderView{
                        background-color:#F9FAFB;
                    }
                    QCalendarWidget QTableView QHeaderView::section{
                        background-color:#F9FAFB;
                        color:#A66A00;
                        padding:6px;
                        border:none;
                        font-weight:600;
                    }
                    QPushButton{
                        border:none;
                        border-radius:10px;
                        padding:8px;
                        font-size:15px;
                        min-height:40px;
                        font-weight:500;
                    }
                    QPushButton#saveBtn{
                        background-color:#16A34A;
                        color:white;
                        font-size:18px;
                        font-weight:400;
                    }
                    QPushButton#saveBtn:hover{
                        background-color:#22C55E;
                    }
                    QPushButton#saveBtn:pressed{
                        background-color:#15803D;
                    }
                    QPushButton#add_habit{
                        background-color:#3B82F6;
                        color:white;
                    }
                    QPushButton#add_habit:hover{
                        background-color:#60A5FA;
                    }
                    QPushButton#add_habit:pressed{
                        background-color:#2563EB;
                    }
                    QPushButton#delete_habit{
                        background-color:#DC2626;
                        color:white;
                    }
                    QPushButton#delete_habit:hover{
                        background-color:#EF4444;
                    }
                    QPushButton#delete_habit:pressed{
                        background-color:#B91C1C;
                    }
                    QTableWidget{
                        background-color:#FFFFFF;
                        color:#1F2937;
                        border:1px solid #E5E7EB;
                        border-radius:10px;
                        gridline-color:#ECECEC;
                        font-size:16px;
                        selection-background-color:transparent;
                        outline:none;
                    }
                    QHeaderView::section{
                        background-color:#F9FAFB;
                        color:#A66A00;
                        border:none;
                        border-bottom:1px solid #E5E7EB;
                        padding:8px;
                        font-size:16px;
                        font-weight:600;
                    }
                    QTableWidget::item:selected{
                        background-color:#EAF3FF;
                        color:#1F2937;
                    }
                    QScrollBar:horizontal{
                        background:#EEF2F7;
                        height:12px;
                        border:none;
                        border-radius:6px;
                    }
                    QScrollBar::handle:horizontal{
                        background:#3B82F6;
                        border-radius:6px;
                        min-width:20px;
                    }
                    QScrollBar::handle:horizontal:hover{
                        background:#60A5FA;
                    }
                    QScrollBar::add-line:horizontal,
                    QScrollBar::sub-line:horizontal{
                        width:0px;
                    }
                    QScrollBar::add-page:horizontal,
                    QScrollBar::sub-page:horizontal{
                        background:none;
                    }
                    QScrollBar:vertical{
                        background:#EEF2F7;
                        width:12px;
                        border:none;
                        border-radius:6px;
                    }
                    QScrollBar::handle:vertical{
                        background:#3B82F6;
                        border-radius:6px;
                        min-height:20px;
                    }
                    QScrollBar::handle:vertical:hover{
                        background:#60A5FA;
                    }
                    QScrollBar::add-line:vertical,
                    QScrollBar::sub-line:vertical{
                        height:0px;
                    }
                    QScrollBar::add-page:vertical,
                    QScrollBar::sub-page:vertical{
                        background:none;
                    }
                    QCheckBox{
                        background:transparent;
                    }
                    QCheckBox::indicator{
                        width:18px;
                        height:18px;
                        border:2px solid rgba(220,38,38,180);
                        border-radius:5px;
                        background-color:rgba(220,38,38,35);
                        image:url("./python/dailytracker/crossL.svg");
                    }
                    QCheckBox::indicator:hover{
                        border:2px solid rgba(239,68,68,220);
                        background-color:rgba(239,68,68,60);
                    }
                    QCheckBox::indicator:pressed{
                        background-color:rgba(239,68,68,90);
                    }
                    QCheckBox::indicator:checked{
                        background-color:rgba(22,163,74,70);
                        border:2px solid rgba(22,163,74,220);
                        image:url("./python/dailytracker/checkL.svg");
                    }
                    QCheckBox::indicator:checked:hover{
                        background-color:rgba(34,197,94,90);
                        border:2px solid rgba(34,197,94,225);
                    }
                    QCheckBox::indicator[future="true"]{
                        background-color:#ECEFF3;
                        border:2px solid #D1D5DB;
                        image:none;
                    }
                    QCheckBox::indicator[before_creation="true"]{
                        background-color:#ECEFF3;
                        border:2px solid #D1D5DB;
                        image:none;
                    }
                    QPushButton#themeToggleBtn{
                        background:transparent;
                        border:none;
                        border-radius:14px;
                        padding:0px;
                    }
                    QPushButton#themeToggleBtn:hover{
                        background-color:rgba(212,160,23,40);
                    }
                    QPushButton#themeToggleBtn:pressed{
                        background-color:rgba(212,160,23,70);
                    }
                    QFrame#bottomBar{
                        background-color:#FFFFFF;
                        border-radius:0px;
                        border-top:1px solid #E5E7EB;
                    }
                    QLabel#bottomBarText{
                        color:#475569;
                        font-size:18px;
                        font-weight:400;
                    }
                    """